# Generated by Django 4.2 on 2026-06-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_verificationtoekn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerificationToekn',
            new_name='VerificationToken',
        ),
    ]
