# Generated by Django 4.2 on 2026-07-30 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponmodel',
            old_name='expiration_data',
            new_name='expiration_date',
        ),
        migrations.RenameField(
            model_name='useraddressmodel',
            old_name='zip_decode',
            new_name='zip_code',
        ),
        migrations.AddField(
            model_name='couponmodel',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.ordermodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.useraddressmodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'در حالت انتظار'), (2, 'در حال پرداخت'), (3, 'ارسال شده'), (4, 'تحویل شده'), (5, 'لغو شده')], default=1),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
