# Generated by Django 4.2 on 2026-08-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_ordermodel_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'در حالت انتظار'), (2, 'در حال پرداخت'), (3, 'پرداخت موفق'), (4, 'پرداخت ناموفق'), (5, 'ارسال شده'), (6, 'لغو شده')], default=1),
        ),
    ]
