# Generated by Django 4.2 on 2026-08-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.IntegerField(choices=[(1, ' در انتظار پرداخت'), (2, 'پرداخت موفق'), (3, 'پرداخت ناموفق')], default=1),
        ),
    ]
