# Generated by Django 4.2 on 2026-08-15 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_paymentmodel_options'),
        ('order', '0008_alter_ordermodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_order', to='payment.paymentmodel'),
        ),
    ]
