# Generated by Django 4.2 on 2026-08-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmodel',
            options={'ordering': ['-created_time'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
