# Generated by Django 4.2 on 2026-09-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_reviewmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'در انتظار تایید'), (2, 'تایید شده '), (3, 'رد شده')], default=1),
        ),
    ]
